#RUN IN TERMINAL: docker pull postgres

version: '2'

services:
  project_database:
    container_name: project_postgres_container
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notifius